### ISSUE TITLE
Double-Check review for REDS (v10)

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LTE_Cat_M1_Shield#1]
1) Are the part libraries consistent with eagle github repo? [YES]
comment: quite a few new parts on this board. They are nicely in a mini ublox.lbr now. Lets try and remember to transfer those into the official libraries after golive.

2) Have all nets been drawn straight out from pin connections at least one grid space? [NO]
comment: GND off of Q2 needs a space

3) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [YES]
comment: C19 needs to be swaped out to 0 ohm resistor and note in sch modified

4) Is the LED color standard followed? (red for power, blue for STAT, green for TX, yellow for RX) [YES]
comment: yellow okay for charge, since right next to red power. blue for stat is standard. right on.

5) As best as possible, do all SMD pads have only 1 trace entering the pad? [YES]
comment: Its a thing of beauty

6) Do all footprints pass 1:1 check?  (Applies mostly to new components) [NO]
comment: TCA9406DCU (new logic converter IC) has not been checked 1:1, but I double-checked data sheet and it looks coorect to me.

7) Is the name of the board on the board? [NO]
comment: New name needs to be updated in silk

8) Does the FTDI connector have BLK/GRN labeled correctly? [NO]
comment: no space

**Comment by dansass** [comment]
Just wondering, did u ever get it going with blynk?
