### ISSUE TITLE
Both Sides of TVS tied to ground

### ISSUE THREAD

**Issue by method-nick** [sparkfun/LTE_Cat_M1_Shield#3]
I'm curious about your wiring of the TVS diode on the SIM card. By connecting both GND and VCC of the diode to the PCB ground the signals can't won't be able to get above the forward voltage of the diodes (1V).

I think the VCC pin of the diode should be connected to the 3V3 rail for correct operation.

**Comment by lewispg228** [comment]
Hi @method-nick 

Thanks for bringing this up. Sorry our response is so slow on this. Sorry for the confusion, but the part value in the schematic for this (v10) is incorrect. 

The part shown in the schematic is "DT1042-04SO"
[DT1042-04SO datasheet](https://www.diodes.com/assets/Datasheets/DT1042-04SO.pdf)

This part is normally used as a unidirectional TVS circuit (which involves connecting to VCC).

In production we are populating a different part. We are actually using the "ESDA6V1BC6".
[ESDA6V1BC6 datasheet](https://static6.arrow.com/aropdfconversion/8da17f9020eacc1aa29eff2b41ce2f0dfe2e4561/cd0000190.pdf)

This part is used as a bidirectional TVS circuit, and so both pins 2 and 5 of the IC are intended to be connected to GND. 

I found some interested articles regarding TVS circuits, if you'd like to read more on this:

[TI FORUM: Should TVS diodes be connected on the Vcc side](https://e2e.ti.com/support/interface/f/138/t/710604)

[TI APP NOTE: Design considerations for system-level
ESD circuit protection](https://www.ti.com/lit/an/slyt492/slyt492.pdf)
(particularly page 3, which describes the difference between unidirectional and bidirection TVS circuits)

Thanks again and we will work to get the part name in the schematic updated in v10 asap.
-Pete
